
quarterback_stats = {
    "Matthew Stafford": {
        "Passing Yards": 2489,
        "Yards per Attempt": 7.3,
        "Completions": 342,
        "Attempts": 208,
        "Completion Percentage": 60.8,
        "Touchdowns": 13,
        "Interceptions": 9,
        "Passer Rating": 84.8,
        "Rushing Attempts": 121,
        "Rushing Yards": 35.4,
        "Rushing Touchdowns": 4,
        "Fumbles": 41,
        "Fumbles Lost": 4,
        "Sacks": 49,
        "Sack Yards Lost": 20,
        "Total Touchdowns": 150
    },
    "Kirk Cousins": {
        "Passing Yards": 2331,
        "Yards per Attempt": 7.5,
        "Completions": 311,
        "Attempts": 216,
        "Completion Percentage": 69.4,
        "Touchdowns": 18,
        "Interceptions": 5,
        "Passer Rating": 103.8,
        "Rushing Attempts": 112,
        "Rushing Yards": 36,
        "Rushing Touchdowns": 4,
        "Fumbles": 34,
        "Fumbles Lost": 4,
        "Sacks": 62,
        "Sack Yards Lost": 17,
        "Total Touchdowns": 110
    },
    "Joe Burrow": {
        "Passing Yards": 2309,
        "Yards per Attempt": 6.3,
        "Completions": 365,
        "Attempts": 244,
        "Completion Percentage": 66.8,
        "Touchdowns": 15,
        "Interceptions": 6,
        "Passer Rating": 91.0,
        "Rushing Attempts": 115,
        "Rushing Yards": 31.5,
        "Rushing Touchdowns": 4,
        "Fumbles": 21,
        "Fumbles Lost": 4,
        "Sacks": 64,
        "Sack Yards Lost": 24,
        "Total Touchdowns": 180
    },
    "Joshua Dobbs": {
        "Passing Yards": 2216,
        "Yards per Attempt": 6.1,
        "Completions": 362,
        "Attempts": 230,
        "Completion Percentage": 63.5,
        "Touchdowns": 12,
        "Interceptions": 6,
        "Passer Rating": 84.7,
        "Rushing Attempts": 113,
        "Rushing Yards": 31.2,
        "Rushing Touchdowns": 2,
        "Fumbles": 27,
        "Fumbles Lost": 2,
        "Sacks": 69,
        "Sack Yards Lost": 23,
        "Total Touchdowns": 154
    },
    "Russell Wilson": {
        "Passing Yards": 2199,
        "Yards per Attempt": 6.9,
        "Completions": 319,
        "Attempts": 218,
        "Completion Percentage": 68.3,
        "Touchdowns": 20,
        "Interceptions": 4,
        "Passer Rating": 103.4,
        "Rushing Attempts": 99,
        "Rushing Yards": 31,
        "Rushing Touchdowns": 5,
        "Fumbles": 26,
        "Fumbles Lost": 5,
        "Sacks": 60,
        "Sack Yards Lost": 33,
        "Total Touchdowns": 164
    },
    "Mac Jones": {
        "Passing Yards": 2120,
        "Yards per Attempt": 6.1,
        "Completions": 345,
        "Attempts": 224,
        "Completion Percentage": 64.9,
        "Touchdowns": 10,
        "Interceptions": 12,
        "Passer Rating": 77.0,
        "Rushing Attempts": 100,
        "Rushing Yards": 29,
        "Rushing Touchdowns": 2,
        "Fumbles": 17,
        "Fumbles Lost": 2,
        "Sacks": 58,
        "Sack Yards Lost": 22,
        "Total Touchdowns": 127
    },
    "Kenny Pickett": {
        "Passing Yards": 2000,
        "Yards per Attempt": 6.4,
        "Completions": 314,
        "Attempts": 194,
        "Completion Percentage": 61.8,
        "Touchdowns": 6,
        "Interceptions": 4,
        "Passer Rating": 81.2,
        "Rushing Attempts": 86,
        "Rushing Yards": 27.4,
        "Rushing Touchdowns": 4,
        "Fumbles": 24,
        "Fumbles Lost": 4,
        "Sacks": 72,
        "Sack Yards Lost": 23,
        "Total Touchdowns": 173
    },
    "Gardner Minshew": {
        "Passing Yards": 1972,
        "Yards per Attempt": 6.6,
        "Completions": 297,
        "Attempts": 187,
        "Completion Percentage": 63.0,
        "Touchdowns": 8,
        "Interceptions": 7,
        "Passer Rating": 81.4,
        "Rushing Attempts": 88,
        "Rushing Yards": 29.6,
        "Rushing Touchdowns": 6,
        "Fumbles": 23,
        "Fumbles Lost": 6,
        "Sacks": 75,
        "Sack Yards Lost": 17,
        "Total Touchdowns": 100
    },
    "Zach Wilson": {
        "Passing Yards": 1944,
        "Yards per Attempt": 6.1,
        "Completions": 321,
        "Attempts": 190,
        "Completion Percentage": 59.2,
        "Touchdowns": 6,
        "Interceptions": 7,
        "Passer Rating": 73.8,
        "Rushing Attempts": 87,
        "Rushing Yards": 27.1,
        "Rushing Touchdowns": 3,
        "Fumbles": 22,
        "Fumbles Lost": 3,
        "Sacks": 68,
        "Sack Yards Lost": 38,
        "Total Touchdowns": 270
    },
    "Sam Howell": {
        "Passing Yards": 3339,
        "Yards per Attempt": 6.9,
        "Completions": 486,
        "Attempts": 323,
        "Completion Percentage": 66.5,
        "Touchdowns": 18,
        "Interceptions": 13,
        "Passer Rating": 87.3,
        "1st Downs": 154,
        "1st Down Percentage": 31.7,
        "20+ Yard Passes": 37,
        "40+ Yard Passes": 3,
        "Longest Pass": 51,
        "Sacks": 55,
        "Sack Yards Lost": 375
    },
    "C.J. Stroud": {
        "Passing Yards": 3266,
        "Yards per Attempt": 8.4,
        "Completions": 391,
        "Attempts": 249,
        "Completion Percentage": 63.7,
        "Touchdowns": 19,
        "Interceptions": 5,
        "Passer Rating": 100.8,
        "1st Downs": 155,
        "1st Down Percentage": 39.6,
        "20+ Yard Passes": 54,
        "40+ Yard Passes": 6,
        "Longest Pass": 75,
        "Sacks": 26,
        "Sack Yards Lost": 235
    },
    "Josh Allen": {
        "Passing Yards": 3214,
        "Yards per Attempt": 7.4,
        "Completions": 433,
        "Attempts": 295,
        "Completion Percentage": 68.1,
        "Touchdowns": 24,
        "Interceptions": 13,
        "Passer Rating": 95.8,
        "1st Downs": 149,
        "1st Down Percentage": 34.4,
        "20+ Yard Passes": 35,
        "40+ Yard Passes": 6,
        "Longest Pass": 81,
        "Sacks": 15,
        "Sack Yards Lost": 83
    },
    "Tua Tagovailoa": {
        "Passing Yards": 3177,
        "Yards per Attempt": 8.4,
        "Completions": 377,
        "Attempts": 263,
        "Completion Percentage": 69.8,
        "Touchdowns": 22,
        "Interceptions": 10,
        "Passer Rating": 103.7,
        "1st Downs": 156,
        "1st Down Percentage": 41.4,
        "20+ Yard Passes": 41,
        "40+ Yard Passes": 7,
        "Longest Pass": 69,
        "Sacks": 17,
        "Sack Yards Lost": 99
    },
    "Jared Goff": {
        "Passing Yards": 3075,
        "Yards per Attempt": 7.6,
        "Completions": 405,
        "Attempts": 275,
        "Completion Percentage": 67.9,
        "Touchdowns": 18,
        "Interceptions": 8,
        "Passer Rating": 96.9,
        "1st Downs": 151,
        "1st Down Percentage": 37.3,
        "20+ Yard Passes": 49,
        "40+ Yard Passes": 5,
        "Longest Pass": 46,
        "Sacks": 20,
        "Sack Yards Lost": 113
    },
    "Dak Prescott": {
        "Passing Yards": 2935,
        "Yards per Attempt": 7.9,
        "Completions": 370,
        "Attempts": 259,
        "Completion Percentage": 70.0,
        "Touchdowns": 23,
        "Interceptions": 6,
        "Passer Rating": 107.4,
        "1st Downs": 142,
        "1st Down Percentage": 38.4,
        "20+ Yard Passes": 46,
        "40+ Yard Passes": 4,
        "Longest Pass": 60,
        "Sacks": 22,
        "Sack Yards Lost": 155
    },
    "Patrick Mahomes": {
        "Passing Yards": 2917,
        "Yards per Attempt": 7.1,
        "Completions": 411,
        "Attempts": 280,
        "Completion Percentage": 68.1,
        "Touchdowns": 21,
        "Interceptions": 9,
        "Passer Rating": 96.3,
        "1st Downs": 145,
        "1st Down Percentage": 35.3,
        "20+ Yard Passes": 32,
        "40+ Yard Passes": 4,
        "Longest Pass": 54,
        "Sacks": 14,
        "Sack Yards Lost": 105
        )
    },
    "Brock Purdy": {
        "Passing Yards": 2871,
        "Yards per Attempt": 9.4,
        "Completions": 214,
        "Attempts": 305,
        "Completion Percentage": 70.2,
        "Touchdowns": 19,
        "Interceptions": 6,
        "Passer Rating": 112.3,
        "Rushing Attempts": 133,
        "Rushing Yards": 43.6,
        "Rushing Touchdowns": 7,
        "Fumbles": 48,
        "Fumbles Lost": 7,
        "Sacks": 76,
        "Sack Yards Lost": 21,
        "Total Touchdowns": 127
    }, "Justin Fields": {
        "Passing Yards": 1370,
        "Yards per Attempt": 7.4,
        "Completions": 116,
        "Attempts": 185,
        "Completion Percentage": 62.7,
        "Touchdowns": 12,
        "Interceptions": 6,
        "Passer Rating": 93.3,
        "1st Downs": 65,
        "1st Down Percentage": 35.1,
        "20+ Yard Passes": 23,
        "40+ Yard Passes": 2,
        "Longest Pass": 58,
        "Sacks": 26,
        "Sack Yards Lost": 161,
        "Total Touchdowns": 98
    },
    "Jimmy Garoppolo": {
        "Passing Yards": 1205,
        "Yards per Attempt": 7.2,
        "Completions": 110,
        "Attempts": 168,
        "Completion Percentage": 65.5,
        "Touchdowns": 7,
        "Interceptions": 9,
        "Passer Rating": 78.1,
        "1st Downs": 60,
        "1st Down Percentage": 35.7,
        "20+ Yard Passes": 9,
        "40+ Yard Passes": 0,
        "Longest Pass": 32,
        "Sacks": 13,
        "Sack Yards Lost": 101,
        "Total Touchdowns": 67
    },
    "Aidan O'Connell": {
        "Passing Yards": 1194,
        "Yards per Attempt": 6.7,
        "Completions": 113,
        "Attempts": 178,
        "Completion Percentage": 63.5,
        "Touchdowns": 4,
        "Interceptions": 6,
        "Passer Rating": 76.4,
        "1st Downs": 56,
        "1st Down Percentage": 31.5,
        "20+ Yard Passes": 11,
        "40+ Yard Passes": 3,
        "Longest Pass": 50,
        "Sacks": 13,
        "Sack Yards Lost": 101,
        "Total Touchdowns": 45
    },
    "Ryan Tannehill": {
        "Passing Yards": 1128,
        "Yards per Attempt": 7.1,
        "Completions": 98,
        "Attempts": 158,
        "Completion Percentage": 62.0,
        "Touchdowns": 2,
        "Interceptions": 6,
        "Passer Rating": 71.9,
        "1st Downs": 49,
        "1st Down Percentage": 31.0,
        "20+ Yard Passes": 17,
        "40+ Yard Passes": 4,
        "Longest Pass": 70,
        "Sacks": 19,
        "Sack Yards Lost": 135,
        "Total Touchdowns": 2
    },
    "Deshaun Watson": {
        "Passing Yards": 1115,
        "Yards per Attempt": 6.5,
        "Completions": 105,
        "Attempts": 171,
        "Completion Percentage": 61.4,
        "Touchdowns": 7,
        "Interceptions": 4,
        "Passer Rating": 84.3,
        "1st Downs": 52,
        "1st Down Percentage": 30.4,
        "20+ Yard Passes": 12,
        "40+ Yard Passes": 3,
        "Longest Pass": 59,
        "Sacks": 17,
        "Sack Yards Lost": 85,
        "Total Touchdowns": 10
    },"Will Levis": {
        "Passing Yards": 1042,
        "Yards per Attempt": 6.9,
        "Completions": 91,
        "Attempts": 152,
        "Completion Percentage": 59.9,
        "Touchdowns": 6,
        "Interceptions": 2,
        "Passer Rating": 88.2,
        "1st Downs": 44,
        "1st Down Percentage": 29.0,
        "20+ Yard Passes": 16,
        "40+ Yard Passes": 4,
        "Longest Pass": 61,
        "Sacks": 13,
        "Sack Yards Lost": 87,
        "Total Touchdowns": 8
    },
    "Daniel Jones": {
        "Passing Yards": 909,
        "Yards per Attempt": 5.7,
        "Completions": 108,
        "Attempts": 160,
        "Completion Percentage": 67.5,
        "Touchdowns": 2,
        "Interceptions": 6,
        "Passer Rating": 70.6,
        "1st Downs": 43,
        "1st Down Percentage": 26.9,
        "20+ Yard Passes": 9,
        "40+ Yard Passes": 1,
        "Longest Pass": 58,
        "Sacks": 30,
        "Sack Yards Lost": 167,
        "Total Touchdowns": 2
    },
    "Tyson Bagent": {
        "Passing Yards": 859,
        "Yards per Attempt": 6.0,
        "Completions": 94,
        "Attempts": 143,
        "Completion Percentage": 65.7,
        "Touchdowns": 3,
        "Interceptions": 6,
        "Passer Rating": 71.4,
        "1st Downs": 48,
        "1st Down Percentage": 33.6,
        "20+ Yard Passes": 3,
        "40+ Yard Passes": 1,
        "Longest Pass": 41,
        "Sacks": 5,
        "Sack Yards Lost": 35,
        "Total Touchdowns": 4
    },
    "Kyler Murray": {
        "Passing Yards": 719,
        "Yards per Attempt": 6.7,
        "Completions": 66,
        "Attempts": 107,
        "Completion Percentage": 61.7,
        "Touchdowns": 2,
        "Interceptions": 2,
        "Passer Rating": 79.9,
        "1st Downs": 33,
        "1st Down Percentage": 30.8,
        "20+ Yard Passes": 8,
        "40+ Yard Passes": 1,
        "Longest Pass": 48,
        "Sacks": 9,
        "Sack Yards Lost": 74,
        "Total Touchdowns": 2
    },
    "Tommy DeVito": {
        "Passing Yards": 697,
        "Yards per Attempt": 6.6,
        "Completions": 66,
        "Attempts": 105,
        "Completion Percentage": 62.9,
        "Touchdowns": 7,
        "Interceptions": 3,
        "Passer Rating": 92.4,
        "1st Downs": 30,
        "1st Down Percentage": 28.6,
        "20+ Yard Passes": 12,
        "40+ Yard Passes": 2,
        "Longest Pass": 41,
        "Sacks": 28,
        "Sack Yards Lost": 137,
        "Total Touchdowns": 10
    },
    "PJ Walker": {
        "Passing Yards": 674,
        "Yards per Attempt": 6.1,
        "Completions": 54,
        "Attempts": 111,
        "Completion Percentage": 48.6,
        "Touchdowns": 1,
        "Interceptions": 5,
        "Passer Rating": 52.2,
        "1st Downs": 27,
        "1st Down Percentage": 24.3,
        "20+ Yard Passes": 11,
        "40+ Yard Passes": 3,
        "Longest Pass": 58,
        "Sacks": 11,
        "Sack Yards Lost": 90,
        "Total Touchdowns": 1
    },
    "Tyrod Taylor": {
        "Passing Yards": 579,
        "Yards per Attempt": 6.7,
        "Completions": 57,
        "Attempts": 87,
        "Completion Percentage": 65.5,
        "Touchdowns": 2,
        "Interceptions": 0,
        "Passer Rating": 92.1,
        "1st Downs": 25,
        "1st Down Percentage": 28.7,
        "20+ Yard Passes": 10,
        "40+ Yard Passes": 1,
        "Longest Pass": 42,
        "Sacks": 10,
        "Sack Yards Lost": 54,
        "Total Touchdowns": 2
    },
    "Anthony Richardson": {
        "Passing Yards": 577,
        "Yards per Attempt": 6.9,
        "Completions": 50,
        "Attempts": 84,
        "Completion Percentage": 59.5,
        "Touchdowns": 3,
        "Interceptions": 1,
        "Passer Rating": 87.2,
        "1st Downs": 31,
        "1st Down Percentage": 36.9,
        "20+ Yard Passes": 9,
        "40+ Yard Passes": 0,
        "Longest Pass": 39,
        "Sacks": 7,
        "Sack Yards Lost": 29,
        "Total Touchdowns": 3
    },
    "Taylor Heinicke": {
        "Passing Yards": 498,
        "Yards per Attempt": 6.7,
        "Completions": 41,
        "Attempts": 74,
        "Completion Percentage": 55.4,
        "Touchdowns": 3,
        "Interceptions": 1,
        "Passer Rating": 84.2,
        "1st Downs": 23,
        "1st Down Percentage": 31.1,
        "20+ Yard Passes": 7,
        "40+ Yard Passes": 2,
        "Longest Pass": 60,
        "Sacks": 5,
        "Sack Yards Lost": 40,
        "Total Touchdowns": 3
    },"Dorian Thompson-Robinson": {
        "Passing Yards": 429,
        "Yards per Attempt": 3.9,
        "Completions": 58,
        "Attempts": 109,
        "Completion Percentage": 53.2,
        "Touchdowns": 1,
        "Interceptions": 4,
        "Passer Rating": 50.6,
        "1st Downs": 24,
        "1st Down Percentage": 22.0,
        "20+ Yard Passes": 1,
        "40+ Yard Passes": 0,
        "Longest Pass": 23,
        "Sacks": 5,
        "Sack Yards Lost": 50,
        "Total Touchdowns": 5
    },
    "Andy Dalton": {
        "Passing Yards": 361,
        "Yards per Attempt": 6.2,
        "Completions": 34,
        "Attempts": 58,
        "Completion Percentage": 58.6,
        "Touchdowns": 2,
        "Interceptions": 0,
        "Passer Rating": 88.4,
        "1st Downs": 17,
        "1st Down Percentage": 29.3,
        "20+ Yard Passes": 5,
        "40+ Yard Passes": 1,
        "Longest Pass": 47,
        "Sacks": 3,
        "Sack Yards Lost": 27,
        "Total Touchdowns": 27
    },
    "Jake Browning": {
        "Passing Yards": 295,
        "Yards per Attempt": 7.2,
        "Completions": 27,
        "Attempts": 41,
        "Completion Percentage": 65.8,
        "Touchdowns": 2,
        "Interceptions": 1,
        "Passer Rating": 93.0,
        "1st Downs": 14,
        "1st Down Percentage": 34.2,
        "20+ Yard Passes": 4,
        "40+ Yard Passes": 0,
        "Longest Pass": 39,
        "Sacks": 7,
        "Sack Yards Lost": 49,
        "Total Touchdowns": 49
    },
    "Brian Hoyer": {
        "Passing Yards": 231,
        "Yards per Attempt": 5.5,
        "Completions": 23,
        "Attempts": 42,
        "Completion Percentage": 54.8,
        "Touchdowns": 0,
        "Interceptions": 2,
        "Passer Rating": 50.8,
        "1st Downs": 14,
        "1st Down Percentage": 33.3,
        "20+ Yard Passes": 2,
        "40+ Yard Passes": 1,
        "Longest Pass": 48,
        "Sacks": 1,
        "Sack Yards Lost": 8,
        "Total Touchdowns": 8
    },
    "Jameis Winston": {
        "Passing Yards": 223,
        "Yards per Attempt": 5.3,
        "Completions": 23,
        "Attempts": 42,
        "Completion Percentage": 54.8,
        "Touchdowns": 2,
        "Interceptions": 3,
        "Passer Rating": 56.0,
        "1st Downs": 8,
        "1st Down Percentage": 19.0,
        "20+ Yard Passes": 3,
        "40+ Yard Passes": 0,
        "Longest Pass": 28,
        "Sacks": 2,
        "Sack Yards Lost": 13,
        "Total Touchdowns": 13
    },
    "Tim Boyle": {
        "Passing Yards": 212,
        "Yards per Attempt": 4.1,
        "Completions": 34,
        "Attempts": 52,
        "Completion Percentage": 65.4,
        "Touchdowns": 1,
        "Interceptions": 3,
        "Passer Rating": 55.9,
        "1st Downs": 10,
        "1st Down Percentage": 19.2,
        "20+ Yard Passes": 0,
        "40+ Yard Passes": 0,
        "Longest Pass": 13,
        "Sacks": 8,
        "Sack Yards Lost": 59,
        "Total Touchdowns": 59
    },
    "Brett Rypien": {
        "Passing Yards": 172,
        "Yards per Attempt": 4.5,
        "Completions": 18,
        "Attempts": 38,
        "Completion Percentage": 47.4,
        "Touchdowns": 0,
        "Interceptions": 1,
        "Passer Rating": 49.4,
        "1st Downs": 8,
        "1st Down Percentage": 21.1,
        "20+ Yard Passes": 1,
        "40+ Yard Passes": 0,
        "Longest Pass": 34,
        "Sacks": 2,
        "Sack Yards Lost": 18,
        "Total Touchdowns": 18
    },
    "Bailey Zappe": {
        "Passing Yards": 158,
        "Yards per Attempt": 4.0,
        "Completions": 19,
        "Attempts": 39,
        "Completion Percentage": 48.7,
        "Touchdowns": 0,
        "Interceptions": 2,
        "Passer Rating": 38.2,
        "1st Downs": 6,
        "1st Down Percentage": 15.8,
        "20+ Yard Passes": 2,
        "40+ Yard Passes": 0,
        "Longest Pass": 22,
        "Sacks": 2,
        "Sack Yards Lost": 14,
        "Total Touchdowns": 14
    },
    "Mitchell Trubisky": {
        "Passing Yards": 156,
        "Yards per Attempt": 4.9,
        "Completions": 18,
        "Attempts": 32,
        "Completion Percentage": 56.2,
        "Touchdowns": 1,
        "Interceptions": 2,
        "Passer Rating": 53.6,
        "1st Downs": 9,
        "1st Down Percentage": 28.1,
        "20+ Yard Passes": 1,
        "40+ Yard Passes": 0,
        "Longest Pass": 22,
        "Sacks": 2,
        "Sack Yards Lost": 15,
        "Total Touchdowns": 4
    }
}